export const logosMap = new Map([
    [33, "man_united"],
    [34, "newcastle"],
    [38, "watford"],
    [39, "wolves"],
    [40, "liverpool"],
    [41, "southampton"],
    [42, "arsenal"],
    [44, "burnley"],
    [45, "everton"],
    [46, "leicester"],
    [47, "tottenham"],
    [48, "west_ham"],
    [49, "chelsea"],
    [50, "man_city"],
    [51, "brighton"],
    [52, "crystal_palace"],
    [55, "brentford"],
    [63, "leeds"],
    [66, "aston_villa"],
    [71, "norwich"],
    [36, "fulham"],
    [60, "west_brom"],
    [62, "sheffield_united"],
    [35, "bournemouth"],
    [37, "huddersfield"],
    [43, "cardiff"],
    [75, "stoke_city"],
    [76, "swansea"],
    [64, "hull_city"],
    [70, "middlesbrough"],
    [746, "sunderland"],
]);

export const namesMap = new Map([
    [33, "Man United"],
    [34, "Newcastle"],
    [38, "Watford"],
    [39, "Wolves"],
    [40, "Liverpool"],
    [41, "Southampton"],
    [42, "Arsenal"],
    [44, "Burnley"],
    [45, "Everton"],
    [46, "Leicester"],
    [47, "Tottenham"],
    [48, "West Ham"],
    [49, "Chelsea"],
    [50, "Man City"],
    [51, "Brighton"],
    [52, "Crystal Palace"],
    [55, "Brentford"],
    [63, "Leeds"],
    [66, "Aston Villa"],
    [71, "Norwich"],
    [36, "Fulham"],
    [60, "West Brom"],
    [62, "Sheffield United"],
    [35, "Bournemouth"],
    [37, "Huddersfield"],
    [43, "Cardiff"],
    [75, "Stoke City"],
    [76, "Swansea"],
    [64, "Hull City"],
    [70, "Middlesbrough"],
    [746, "Sunderland"],
]);
